name: Issue Triggered Workflow

on:
  issues:
    types: [opened]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Bug Label
        if: contains(github.event.issue.title, 'deploy:')
        run: |
          echo "User name is ${{ github.actor }}"
          echo "Issue title is ${{ github.event.issue.title }}"
          echo "Issue body is ${{ github.event.issue.body }}"
          echo "$GITHUB_CONTEXT"
        env:
            GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Generate artifact
        run: |
          echo "SECRET ${{ secrets.DUMMY_SECRET }}" > $GITHUB_WORKSPACE/artifact.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: $GITHUB_WORKSPACE/artifact.txt
    
          
        
