name: Issue Triggered Workflow

on:
  issues:
    types: [opened]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Bug Label
        if: contains(github.event.issue.title, 'deploy')
        run: |
          echo "User name is ${{ github.actor }}"
          echo "${{ toJson(github.event.issue) }}"