name: Issue Triggered Workflow

on:
  issues:
    types: [opened]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Bug Label
        run: |
          echo "User name is ${{ github.actor }}"
          echo "Issue title is ${{ github.event.issue.title }}"
          echo "Issue body is ${{ github.event.issue.body }}"
          echo "Issue is ${{ toJson(github.event.issue) }}"
