on: push
    

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Running tests"

  call-sub-worflow:
    uses: pierresendorek/gha/.github/workflows/triggered.yml@fix-broken-workflows